// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa2ENRIF-yzPrvVpn3N0L_FEqgYWmQ_Ho',
    appId: '1:210433876528:web:708fd0c0d665f7a24643f5',
    messagingSenderId: '210433876528',
    projectId: 'waypoint-dc65c',
    authDomain: 'waypoint-dc65c.firebaseapp.com',
    storageBucket: 'waypoint-dc65c.firebasestorage.app',
    measurementId: 'G-7VJVRV1EHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI1J1YyOyMPhW4kSrE71T7jDf2AwjeoQE',
    appId: '1:210433876528:android:5a098e3acc06df364643f5',
    messagingSenderId: '210433876528',
    projectId: 'waypoint-dc65c',
    storageBucket: 'waypoint-dc65c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRirdK_bUvPBuMooY1cOfSg6DpXqagzi0',
    appId: '1:210433876528:ios:8fdc00a0b508dfe54643f5',
    messagingSenderId: '210433876528',
    projectId: 'waypoint-dc65c',
    storageBucket: 'waypoint-dc65c.firebasestorage.app',
    iosBundleId: 'com.example.waypoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRirdK_bUvPBuMooY1cOfSg6DpXqagzi0',
    appId: '1:210433876528:ios:8fdc00a0b508dfe54643f5',
    messagingSenderId: '210433876528',
    projectId: 'waypoint-dc65c',
    storageBucket: 'waypoint-dc65c.firebasestorage.app',
    iosBundleId: 'com.example.waypoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa2ENRIF-yzPrvVpn3N0L_FEqgYWmQ_Ho',
    appId: '1:210433876528:web:32249644a4c6bb554643f5',
    messagingSenderId: '210433876528',
    projectId: 'waypoint-dc65c',
    authDomain: 'waypoint-dc65c.firebaseapp.com',
    storageBucket: 'waypoint-dc65c.firebasestorage.app',
    measurementId: 'G-F1DEE32QV3',
  );
}
