name: waypoint
description: A visually stunning event planning app
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  shared_preferences: ^2.2.0
  firebase_vertexai: ^1.4.0
  geocoding: ^3.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env